version: '3'
services:
  gitlab_mysql:
    container_name: "gitlab_mysql"
    image: sameersbn/mysql:latest
    ports:
    - "3336:3306"
    volumes:
    - /volume1/docker/mysql:/var/lib/mysql
    env_file: 
    - ./gitlab.env
  
  gitlab_redis:
    container_name: "gitlab_redis"
    image: sameersbn/redis:latest
    volumes:
    - /volume1/docker/redis:/var/lib/redis
    env_file: 
    - ./gitlab.env

  gitlab:
    container_name: "gitlab"
    image: sameersbn/gitlab:10.2.2
    volumes:
    - /volume1/docker/gitlab:/home/git/data
    env_file: 
    - ./gitlab.env
    links:
    - gitlab_mysql:mysql
    - gitlab_redis:redisio
    ports:
    - "30001:22" 
    - "30000:80"
